@echo off
goto :MirumX.API

This API cleans temporary files generated by MirumX
USAGE:
	
	Cleanup

:MirumX.API
:: Delete temporary files generated by API.FileSegment
	if exist "..\*.tmp" (del ..\*.tmp >nul 2>&1)
:: Delete temporary file generated by API.FileSegment
	if exist "APIs\timer.txt" (del APIs\timer.txt >nul 2>&1)